account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from account.views import ProfileView
from account import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('<str:key>/', views.append_site, name='new_site_owner'),
    path('profile/', ProfileView, name='profile')
]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api import views
from api.stickers.views import StickerViewSet
from api.views import WorkAreaApiView, CustomAuthToken
from api.stickers import views as sticker_views

app_name = 'api'

router = DefaultRouter()
router.register('stickers', StickerViewSet, basename='sticker')

urlpatterns = [
    # Url for token
    path('getToken/', CustomAuthToken.as_view(), name='get_token'),
    # Urls for workArea
    path('workArea/', WorkAreaApiView.as_view(), name='work_area_api_view'),
    path('uploadSticker/', views.upload_stickers, name='upload_sticker'),
    path('chooseLaptop/', views.choose_laptop, name='choose_laptop'),
    path('searchByTags/', views.search_by_tags, name='search_by_tags'),
    path('chooseLaptopManufacturer/', views.choose_laptop_manufacturer, name='choose_laptop_manufacturer'),

    # Urls for stickers
    path('', include(router.urls)),
]

laptopstickers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from laptop import urls as laptopUrls
from stickers import urls as stickerUrls
from workArea import urls as placerUrls
from api import urls as apiUrls
from account import urls as accountUrls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('laptop/', include(laptopUrls, namespace='laptop')),
    path('sticker/', include(stickerUrls, namespace='sticker')),
    path('', include(placerUrls, namespace='workArea')),
    path('api/', include(apiUrls, namespace='api')),
    path('account/', include(accountUrls, namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workArea/urls.py
from django.urls import path

from workArea.views import Placer

app_name = 'workArea'

urlpatterns = [
    path('', Placer.as_view(), name='workArea'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block style %}   {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    </head>
    <body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg ">
             <a class="navbar-brand" style="padding-top:0; padding-bottom:0;" href="{% url 'workArea:workArea' %}">
            <img src="{% static 'labels/logo.png' %}" width="320" height="65" class="d-inline-block align-top" alt="" loading="lazy">
            </a>
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/laptop/' %}active {% endif %}" href="/laptop">Laptops</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/sticker/' %}active {% endif %}" href="/sticker">Stickers</a>
                  </li>
                     {% if request.user.is_authenticated %}
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ request.user }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="">Profile</a>
                                  <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                            </div>
                          </li>
                     {% else %}
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                         </li>
                     {% endif %}
                </ul>
        </nav>
        <hr>
    </div>
        <div class="container-fluid" id="laptopStickers">
            {% block content %}{% endblock %}
        </div>
        <script>
            let stickers_site_url = '';
            let api_or_not = '';
        </script>
        {% block scripts %} {% endblock %}
    </body>
</html>